### ISSUE TITLE
quantized parameters not perfect quantized.

### ISSUE THREAD

**Issue by knuds** [AIworx-Labs/chocolate#10]
When I use quantized_uniform(0.0, 1.0,0.01) i still get parameters like:

0.27000000000000002
0.17999999999999999
0.85999999999999999
instead of 
0.27
0.18
0.86

**Comment by fmder** [comment]
Yes, this is only due to floating point limited accuracy.

**Comment by knuds** [comment]
or a missing round(x/step)*step
