### ISSUE TITLE
PyPI release?

### ISSUE THREAD

**Issue by hbredin** [AIworx-Labs/chocolate#16]
I really like the "distributed + SQLite" feature of chocolate (which I couldn't find in any other hyper-parameter optimization Python tool) and therefore plan to use it in one of my project.

However, I don't want to link to the (moving) master branch of this repository.
Are there any plan to make proper PyPI releases of chocolate?

**Comment by fmder** [comment]
We should have PyPi soon. Stay tuned.

**Comment by hbredin** [comment]
Sorry for bothering you again: any news regarding a PyPI release? 

As of today, I cannot find a way to use "git+https://github.com/AIworx-Labs/chocolate@master" in my project's  "setup.py" and have to ask my users to "pip install" chocolate separately. 

I will probably keep using chocolate anyway but, still, a PyPI release would make your great library much more usable and easy to discover for new users...
