### ISSUE TITLE
Error in "Optimizing Over Multiple Models" example

### ISSUE THREAD

**Issue by Codeguyross** [AIworx-Labs/chocolate#18]
The score_svm example on the Optimizing Over Multiple Models has the following function definition:

`def score_svm(X, y, algo, **params):`

When the score_svm function is called, it is called without the algo parameter (see below). What is actually supposed to be sent for the algo parameter?
`loss = score_svm(X, y, **params)`

**Comment by fmder** [comment]
When calling, the algo is in the params. I agree that the different signature can be confusing.

**Comment by Codeguyross** [comment]
Im sorry, I dont quite understand. It doesnt run without algo in the params and throws an error. What is suppose to be in the paramter algo?

**Comment by fmder** [comment]
``algo`` is a parameter returned by ``next()``. The returned dictionary should contain a key "algo".

**Comment by Codeguyross** [comment]
Ok, were getting somewhere but its not quite working yet

```
from sklearn.datasets import make_classification
X, y = make_classification(n_samples=80000, random_state=1)
conn = choco.SQLiteConnection(url="sqlite:///db.db")
sampler = choco.QuasiRandom(conn, space, seed=42, skip=0, clear_db=True)
token, params = sampler.next()
```

```
params
{'C': 100.0,
 'algo': sklearn.svm.classes.SVC,
 'gamma': 6.309573444801943e-05,
 'kernel': 'rbf'}
```

```
params['algo']
sklearn.svm.classes.SVC
```

```
algo= params['algo']
loss = score_svm(X, y, algo, **params)
sampler.update(token, loss)
```

Produces this error
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-2b6ad5188828> in <module>()
      1 algo= params['algo']
      2 
----> 3 loss = score_svm(X, y, algo, **params)
      4 sampler.update(token, loss)

TypeError: score_svm() got multiple values for argument 'algo'

```

Thanks for the help!

**Comment by fmder** [comment]
Yes because it is already in the params dictionary. What is your version of
Python?

Le jeu. 13 déc. 2018 13 h 47, Codeguyross <notifications@github.com> a
écrit :
